### PR TITLE
Organize concurrent read dependencies

### PR DESCRIPTION
**Pull request by dialecticDolt**
This PR is the same as the old one. 

Changes (most of which are implemented in a really lazy way):
- Merge in CV Parray changes
- Compute tasks that use a data block as IN are never used as a dependee
- OUT data movement tasks are removed (since this is just INOUT)
- All data movement tasks now only perform read operations
- Write operations are performed at the start of compute tasks. 
---- In the current PR, this is done with auto_move(). Optimally movement should never occur. 

 Note: This PR is the same as the old one. 

Changes (most of which are implemented in a really lazy way):
- Merge in CV Parray changes
- Compute tasks that use a data block as IN are never used as a dependee
- OUT data movement tasks are removed (since this is just INOUT)
- All data movement tasks now only perform read operations
- Write operations are performed at the start of compute tasks. 
---- In the current PR, this is done with auto_move(). Optimally movement should never occur. 

 Note: 
**I think this has the same hanging bug as current dev. Making this PR because I'm not sure its a new different cause, review with caution!**

task

^ removing red edges in this picture, to allow blue edges to happen concurrently.

### CODE REVIEW

**Comment by dialecticDolt** [comment]
ah ignore this. Forgot to push some changes!

**Comment by dialecticDolt** [comment]
Now its updated.

**Comment by yinengy** [comment]
condition variable changes are included in #119

**Comment by dialecticDolt** [comment]
Closing this because my other PR includes this. Whoops.

**Pull request closed without merging**
